// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/compliance.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FindingRequest contains a detected PII instance
type FindingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanId        string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`                   // UUID of the scan job
	ResourceId    string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`       // Resource identifier (s3://bucket/key or rds://instance/db/table)
	ResourceType  string                 `protobuf:"bytes,3,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"` // 's3_object' or 'rds_table'
	ResourceName  string                 `protobuf:"bytes,4,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"` // Human-readable name
	Region        string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`                                 // AWS region
	SizeBytes     int64                  `protobuf:"varint,6,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`         // Resource size
	PiiDetection  *PIIDetection          `protobuf:"bytes,7,opt,name=pii_detection,json=piiDetection,proto3" json:"pii_detection,omitempty"` // The detected PII
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindingRequest) Reset() {
	*x = FindingRequest{}
	mi := &file_proto_compliance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindingRequest) ProtoMessage() {}

func (x *FindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compliance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindingRequest.ProtoReflect.Descriptor instead.
func (*FindingRequest) Descriptor() ([]byte, []int) {
	return file_proto_compliance_proto_rawDescGZIP(), []int{0}
}

func (x *FindingRequest) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *FindingRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *FindingRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *FindingRequest) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *FindingRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *FindingRequest) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FindingRequest) GetPiiDetection() *PIIDetection {
	if x != nil {
		return x.PiiDetection
	}
	return nil
}

// PIIDetection represents a single PII finding
type PIIDetection struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PiiType         string                 `protobuf:"bytes,1,opt,name=pii_type,json=piiType,proto3" json:"pii_type,omitempty"`                           // 'aadhaar', 'pan', 'gstin', 'phone', 'voter_id'
	ConfidenceScore float32                `protobuf:"fixed32,2,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"` // 0.0 to 1.0
	SampleData      string                 `protobuf:"bytes,3,opt,name=sample_data,json=sampleData,proto3" json:"sample_data,omitempty"`                  // Masked sample for verification
	RiskLevel       string                 `protobuf:"bytes,4,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`                     // 'critical', 'high', 'medium', 'low'
	DpdpSection     string                 `protobuf:"bytes,5,opt,name=dpdp_section,json=dpdpSection,proto3" json:"dpdp_section,omitempty"`               // DPDP Act 2023 section reference
	Location        *LocationInfo          `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`                                        // Where the PII was found
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PIIDetection) Reset() {
	*x = PIIDetection{}
	mi := &file_proto_compliance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PIIDetection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PIIDetection) ProtoMessage() {}

func (x *PIIDetection) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compliance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PIIDetection.ProtoReflect.Descriptor instead.
func (*PIIDetection) Descriptor() ([]byte, []int) {
	return file_proto_compliance_proto_rawDescGZIP(), []int{1}
}

func (x *PIIDetection) GetPiiType() string {
	if x != nil {
		return x.PiiType
	}
	return ""
}

func (x *PIIDetection) GetConfidenceScore() float32 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *PIIDetection) GetSampleData() string {
	if x != nil {
		return x.SampleData
	}
	return ""
}

func (x *PIIDetection) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *PIIDetection) GetDpdpSection() string {
	if x != nil {
		return x.DpdpSection
	}
	return ""
}

func (x *PIIDetection) GetLocation() *LocationInfo {
	if x != nil {
		return x.Location
	}
	return nil
}

// LocationInfo describes where PII was detected
type LocationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LineNumber    int32                  `protobuf:"varint,1,opt,name=line_number,json=lineNumber,proto3" json:"line_number,omitempty"` // For text files
	ColumnName    string                 `protobuf:"bytes,2,opt,name=column_name,json=columnName,proto3" json:"column_name,omitempty"`  // For structured data
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`                           // Byte offset in file
	FieldPath     string                 `protobuf:"bytes,4,opt,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`     // JSON path or column hierarchy
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationInfo) Reset() {
	*x = LocationInfo{}
	mi := &file_proto_compliance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationInfo) ProtoMessage() {}

func (x *LocationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compliance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationInfo.ProtoReflect.Descriptor instead.
func (*LocationInfo) Descriptor() ([]byte, []int) {
	return file_proto_compliance_proto_rawDescGZIP(), []int{2}
}

func (x *LocationInfo) GetLineNumber() int32 {
	if x != nil {
		return x.LineNumber
	}
	return 0
}

func (x *LocationInfo) GetColumnName() string {
	if x != nil {
		return x.ColumnName
	}
	return ""
}

func (x *LocationInfo) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *LocationInfo) GetFieldPath() string {
	if x != nil {
		return x.FieldPath
	}
	return ""
}

// FindingResponse acknowledges receipt of finding
type FindingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FindingId     int32                  `protobuf:"varint,3,opt,name=finding_id,json=findingId,proto3" json:"finding_id,omitempty"` // Database ID of recorded finding
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindingResponse) Reset() {
	*x = FindingResponse{}
	mi := &file_proto_compliance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindingResponse) ProtoMessage() {}

func (x *FindingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compliance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindingResponse.ProtoReflect.Descriptor instead.
func (*FindingResponse) Descriptor() ([]byte, []int) {
	return file_proto_compliance_proto_rawDescGZIP(), []int{3}
}

func (x *FindingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FindingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FindingResponse) GetFindingId() int32 {
	if x != nil {
		return x.FindingId
	}
	return 0
}

// ProgressRequest updates scan job progress
type ProgressRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ScanId           string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	ProgressPercent  int32                  `protobuf:"varint,2,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"` // 0-100
	ResourcesScanned int32                  `protobuf:"varint,3,opt,name=resources_scanned,json=resourcesScanned,proto3" json:"resources_scanned,omitempty"`
	FindingsCount    int32                  `protobuf:"varint,4,opt,name=findings_count,json=findingsCount,proto3" json:"findings_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProgressRequest) Reset() {
	*x = ProgressRequest{}
	mi := &file_proto_compliance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressRequest) ProtoMessage() {}

func (x *ProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compliance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressRequest.ProtoReflect.Descriptor instead.
func (*ProgressRequest) Descriptor() ([]byte, []int) {
	return file_proto_compliance_proto_rawDescGZIP(), []int{4}
}

func (x *ProgressRequest) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *ProgressRequest) GetProgressPercent() int32 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *ProgressRequest) GetResourcesScanned() int32 {
	if x != nil {
		return x.ResourcesScanned
	}
	return 0
}

func (x *ProgressRequest) GetFindingsCount() int32 {
	if x != nil {
		return x.FindingsCount
	}
	return 0
}

// ProgressResponse acknowledges progress update
type ProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressResponse) Reset() {
	*x = ProgressResponse{}
	mi := &file_proto_compliance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressResponse) ProtoMessage() {}

func (x *ProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compliance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressResponse.ProtoReflect.Descriptor instead.
func (*ProgressResponse) Descriptor() ([]byte, []int) {
	return file_proto_compliance_proto_rawDescGZIP(), []int{5}
}

func (x *ProgressResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProgressResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// CompleteRequest marks scan as complete
type CompleteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ScanId         string                 `protobuf:"bytes,1,opt,name=scan_id,json=scanId,proto3" json:"scan_id,omitempty"`
	Success        bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Empty if successful
	TotalResources int32                  `protobuf:"varint,4,opt,name=total_resources,json=totalResources,proto3" json:"total_resources,omitempty"`
	TotalFindings  int32                  `protobuf:"varint,5,opt,name=total_findings,json=totalFindings,proto3" json:"total_findings,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CompleteRequest) Reset() {
	*x = CompleteRequest{}
	mi := &file_proto_compliance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRequest) ProtoMessage() {}

func (x *CompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compliance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRequest.ProtoReflect.Descriptor instead.
func (*CompleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_compliance_proto_rawDescGZIP(), []int{6}
}

func (x *CompleteRequest) GetScanId() string {
	if x != nil {
		return x.ScanId
	}
	return ""
}

func (x *CompleteRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CompleteRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CompleteRequest) GetTotalResources() int32 {
	if x != nil {
		return x.TotalResources
	}
	return 0
}

func (x *CompleteRequest) GetTotalFindings() int32 {
	if x != nil {
		return x.TotalFindings
	}
	return 0
}

// CompleteResponse acknowledges completion
type CompleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteResponse) Reset() {
	*x = CompleteResponse{}
	mi := &file_proto_compliance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteResponse) ProtoMessage() {}

func (x *CompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compliance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteResponse.ProtoReflect.Descriptor instead.
func (*CompleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_compliance_proto_rawDescGZIP(), []int{7}
}

func (x *CompleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CompleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_compliance_proto protoreflect.FileDescriptor

const file_proto_compliance_proto_rawDesc = "" +
	"\n" +
	"\x16proto/compliance.proto\x12\x05aurva\"\x85\x02\n" +
	"\x0eFindingRequest\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\x12#\n" +
	"\rresource_type\x18\x03 \x01(\tR\fresourceType\x12#\n" +
	"\rresource_name\x18\x04 \x01(\tR\fresourceName\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x06 \x01(\x03R\tsizeBytes\x128\n" +
	"\rpii_detection\x18\a \x01(\v2\x13.aurva.PIIDetectionR\fpiiDetection\"\xe8\x01\n" +
	"\fPIIDetection\x12\x19\n" +
	"\bpii_type\x18\x01 \x01(\tR\apiiType\x12)\n" +
	"\x10confidence_score\x18\x02 \x01(\x02R\x0fconfidenceScore\x12\x1f\n" +
	"\vsample_data\x18\x03 \x01(\tR\n" +
	"sampleData\x12\x1d\n" +
	"\n" +
	"risk_level\x18\x04 \x01(\tR\triskLevel\x12!\n" +
	"\fdpdp_section\x18\x05 \x01(\tR\vdpdpSection\x12/\n" +
	"\blocation\x18\x06 \x01(\v2\x13.aurva.LocationInfoR\blocation\"\x87\x01\n" +
	"\fLocationInfo\x12\x1f\n" +
	"\vline_number\x18\x01 \x01(\x05R\n" +
	"lineNumber\x12\x1f\n" +
	"\vcolumn_name\x18\x02 \x01(\tR\n" +
	"columnName\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x1d\n" +
	"\n" +
	"field_path\x18\x04 \x01(\tR\tfieldPath\"d\n" +
	"\x0fFindingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"finding_id\x18\x03 \x01(\x05R\tfindingId\"\xa9\x01\n" +
	"\x0fProgressRequest\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x12)\n" +
	"\x10progress_percent\x18\x02 \x01(\x05R\x0fprogressPercent\x12+\n" +
	"\x11resources_scanned\x18\x03 \x01(\x05R\x10resourcesScanned\x12%\n" +
	"\x0efindings_count\x18\x04 \x01(\x05R\rfindingsCount\"F\n" +
	"\x10ProgressResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb9\x01\n" +
	"\x0fCompleteRequest\x12\x17\n" +
	"\ascan_id\x18\x01 \x01(\tR\x06scanId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12'\n" +
	"\x0ftotal_resources\x18\x04 \x01(\x05R\x0etotalResources\x12%\n" +
	"\x0etotal_findings\x18\x05 \x01(\x05R\rtotalFindings\"F\n" +
	"\x10CompleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xe0\x01\n" +
	"\x11ComplianceService\x12C\n" +
	"\x12ReportCloudFinding\x12\x15.aurva.FindingRequest\x1a\x16.aurva.FindingResponse\x12E\n" +
	"\x12ReportScanProgress\x12\x16.aurva.ProgressRequest\x1a\x17.aurva.ProgressResponse\x12?\n" +
	"\fCompleteScan\x12\x16.aurva.CompleteRequest\x1a\x17.aurva.CompleteResponseB*Z(github.com/aurva/compliance-engine/protob\x06proto3"

var (
	file_proto_compliance_proto_rawDescOnce sync.Once
	file_proto_compliance_proto_rawDescData []byte
)

func file_proto_compliance_proto_rawDescGZIP() []byte {
	file_proto_compliance_proto_rawDescOnce.Do(func() {
		file_proto_compliance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_compliance_proto_rawDesc), len(file_proto_compliance_proto_rawDesc)))
	})
	return file_proto_compliance_proto_rawDescData
}

var file_proto_compliance_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_compliance_proto_goTypes = []any{
	(*FindingRequest)(nil),   // 0: aurva.FindingRequest
	(*PIIDetection)(nil),     // 1: aurva.PIIDetection
	(*LocationInfo)(nil),     // 2: aurva.LocationInfo
	(*FindingResponse)(nil),  // 3: aurva.FindingResponse
	(*ProgressRequest)(nil),  // 4: aurva.ProgressRequest
	(*ProgressResponse)(nil), // 5: aurva.ProgressResponse
	(*CompleteRequest)(nil),  // 6: aurva.CompleteRequest
	(*CompleteResponse)(nil), // 7: aurva.CompleteResponse
}
var file_proto_compliance_proto_depIdxs = []int32{
	1, // 0: aurva.FindingRequest.pii_detection:type_name -> aurva.PIIDetection
	2, // 1: aurva.PIIDetection.location:type_name -> aurva.LocationInfo
	0, // 2: aurva.ComplianceService.ReportCloudFinding:input_type -> aurva.FindingRequest
	4, // 3: aurva.ComplianceService.ReportScanProgress:input_type -> aurva.ProgressRequest
	6, // 4: aurva.ComplianceService.CompleteScan:input_type -> aurva.CompleteRequest
	3, // 5: aurva.ComplianceService.ReportCloudFinding:output_type -> aurva.FindingResponse
	5, // 6: aurva.ComplianceService.ReportScanProgress:output_type -> aurva.ProgressResponse
	7, // 7: aurva.ComplianceService.CompleteScan:output_type -> aurva.CompleteResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_compliance_proto_init() }
func file_proto_compliance_proto_init() {
	if File_proto_compliance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_compliance_proto_rawDesc), len(file_proto_compliance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_compliance_proto_goTypes,
		DependencyIndexes: file_proto_compliance_proto_depIdxs,
		MessageInfos:      file_proto_compliance_proto_msgTypes,
	}.Build()
	File_proto_compliance_proto = out.File
	file_proto_compliance_proto_goTypes = nil
	file_proto_compliance_proto_depIdxs = nil
}
