// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: proto/compliance.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ComplianceService_ReportCloudFinding_FullMethodName = "/aurva.ComplianceService/ReportCloudFinding"
	ComplianceService_ReportScanProgress_FullMethodName = "/aurva.ComplianceService/ReportScanProgress"
	ComplianceService_CompleteScan_FullMethodName       = "/aurva.ComplianceService/CompleteScan"
)

// ComplianceServiceClient is the client API for ComplianceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ComplianceService handles findings from cloud scanners
type ComplianceServiceClient interface {
	// ReportCloudFinding is called by scanners to report PII detections
	ReportCloudFinding(ctx context.Context, in *FindingRequest, opts ...grpc.CallOption) (*FindingResponse, error)
	// ReportScanProgress updates scan job progress
	ReportScanProgress(ctx context.Context, in *ProgressRequest, opts ...grpc.CallOption) (*ProgressResponse, error)
	// CompleteScan marks a scan job as complete
	CompleteScan(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (*CompleteResponse, error)
}

type complianceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewComplianceServiceClient(cc grpc.ClientConnInterface) ComplianceServiceClient {
	return &complianceServiceClient{cc}
}

func (c *complianceServiceClient) ReportCloudFinding(ctx context.Context, in *FindingRequest, opts ...grpc.CallOption) (*FindingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindingResponse)
	err := c.cc.Invoke(ctx, ComplianceService_ReportCloudFinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *complianceServiceClient) ReportScanProgress(ctx context.Context, in *ProgressRequest, opts ...grpc.CallOption) (*ProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProgressResponse)
	err := c.cc.Invoke(ctx, ComplianceService_ReportScanProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *complianceServiceClient) CompleteScan(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (*CompleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteResponse)
	err := c.cc.Invoke(ctx, ComplianceService_CompleteScan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ComplianceServiceServer is the server API for ComplianceService service.
// All implementations must embed UnimplementedComplianceServiceServer
// for forward compatibility.
//
// ComplianceService handles findings from cloud scanners
type ComplianceServiceServer interface {
	// ReportCloudFinding is called by scanners to report PII detections
	ReportCloudFinding(context.Context, *FindingRequest) (*FindingResponse, error)
	// ReportScanProgress updates scan job progress
	ReportScanProgress(context.Context, *ProgressRequest) (*ProgressResponse, error)
	// CompleteScan marks a scan job as complete
	CompleteScan(context.Context, *CompleteRequest) (*CompleteResponse, error)
	mustEmbedUnimplementedComplianceServiceServer()
}

// UnimplementedComplianceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedComplianceServiceServer struct{}

func (UnimplementedComplianceServiceServer) ReportCloudFinding(context.Context, *FindingRequest) (*FindingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportCloudFinding not implemented")
}
func (UnimplementedComplianceServiceServer) ReportScanProgress(context.Context, *ProgressRequest) (*ProgressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportScanProgress not implemented")
}
func (UnimplementedComplianceServiceServer) CompleteScan(context.Context, *CompleteRequest) (*CompleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteScan not implemented")
}
func (UnimplementedComplianceServiceServer) mustEmbedUnimplementedComplianceServiceServer() {}
func (UnimplementedComplianceServiceServer) testEmbeddedByValue()                           {}

// UnsafeComplianceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ComplianceServiceServer will
// result in compilation errors.
type UnsafeComplianceServiceServer interface {
	mustEmbedUnimplementedComplianceServiceServer()
}

func RegisterComplianceServiceServer(s grpc.ServiceRegistrar, srv ComplianceServiceServer) {
	// If the following call panics, it indicates UnimplementedComplianceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ComplianceService_ServiceDesc, srv)
}

func _ComplianceService_ReportCloudFinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComplianceServiceServer).ReportCloudFinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComplianceService_ReportCloudFinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComplianceServiceServer).ReportCloudFinding(ctx, req.(*FindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComplianceService_ReportScanProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComplianceServiceServer).ReportScanProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComplianceService_ReportScanProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComplianceServiceServer).ReportScanProgress(ctx, req.(*ProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComplianceService_CompleteScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComplianceServiceServer).CompleteScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComplianceService_CompleteScan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComplianceServiceServer).CompleteScan(ctx, req.(*CompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ComplianceService_ServiceDesc is the grpc.ServiceDesc for ComplianceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ComplianceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aurva.ComplianceService",
	HandlerType: (*ComplianceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportCloudFinding",
			Handler:    _ComplianceService_ReportCloudFinding_Handler,
		},
		{
			MethodName: "ReportScanProgress",
			Handler:    _ComplianceService_ReportScanProgress_Handler,
		},
		{
			MethodName: "CompleteScan",
			Handler:    _ComplianceService_CompleteScan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/compliance.proto",
}
